import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function All() {

const router = useRouter()
const routes = router.query.all

  return (
    <div className={styles.container}>
      {/* {styles.container} - container klassini styles faylindan buraya verir eslinde */}
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {routes?.map((r, i) => (
        <h1 key={i}> + {r}</h1>
      ))}
      
    </div>
  )
}
